//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialDatas
    {
        public int Id { get; set; }
        public string User_Id { get; set; }
        public string Message { get; set; }
        public string Language { get; set; }
        public string User_Location { get; set; }
        public string User_Name { get; set; }
        public string User_Time_Zone { get; set; }
        public string Place_Region { get; set; }
        public string Place_Country { get; set; }
        public string Geo_Latitude { get; set; }
        public string Geo_Longitude { get; set; }
        public string Sentiment { get; set; }
        public string Date_Time { get; set; }
        public string FilterKeyword { get; set; }
        public string RetweetsCount { get; set; }
    }
}
